theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

title: "My Site"
description: "Personal website"
name: "Me"

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

markdown_ext: "md,markdown,html"