remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark"

title: "My Site"
name: "My Name"
description: "My website."

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge